services:
  - type: web
    name: api-hugo-backend
    runtime: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: NYTIMES_API_KEY
        sync: false
      - key: FRONTEND_ORIGINS
        value: https://front-hugo-api.vercel.app
      - key: NYT_BOOKS_BASE_URL
        value: https://api.nytimes.com/svc/books/v3
      - key: NYT_SEARCH_BASE_URL
        value: https://api.nytimes.com/svc/search/v2
